spring:
  datasource:
    url: jdbc:postgresql://82.146.62.204:5432/postgres
    username: postgres
    password: postgres
    driver: com.mysql.jdbc.Driver
    mvc:
      static-path-pattern=/resources/**:
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  logging:
    level:
      org.springframework.web: DEBUG
      org.hibernate: ALL
      root: DEBUG
    pattern:
      console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
      file: "%d %p %c{1.} [%t] %m%n"
    file: app.log
localization: ru

