server:
  port: 9595
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    mvc:
      static-path-pattern=/resources/**:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: update
      jdbc:
        lob:
          non_contextual_creation: true
    show-sql: true
  logging:
    level:
      org.springframework.web: DEBUG
      org.hibernate: ALL
      root: DEBUG
    pattern:
      console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
      file: "%d %p %c{1.} [%t] %m%n"
    file: app.log
localization: ru
upload:
  path: C:\Users\HP\Documents\IdeaProjects\!OTUS\14\booklibrary\images
